# Generated by Django 5.0.6 on 2025-02-09 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='MKID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='api.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.eventcategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='MKID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.event'),
        ),
        migrations.AddField(
            model_name='registeredevents',
            name='MKID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.event'),
        ),
        migrations.AddField(
            model_name='winner',
            name='MKID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='winner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='api.event'),
        ),
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together={('MKID', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='registeredevents',
            unique_together={('MKID', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together={('event', 'position')},
        ),
    ]
