# Generated by Django 4.2.19 on 2025-02-24 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_coordinator_coordinator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='MKID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
