# Generated by Django 5.0.6 on 2025-03-12 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_coordinator_mkid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registeredevents',
            unique_together={('MKID',)},
        ),
        migrations.AddField(
            model_name='registeredevents',
            name='event_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='registeredevents',
            name='event',
        ),
    ]
