# Generated by Django 5.0.6 on 2025-03-12 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_registeredevents_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registeredevents',
            unique_together={('MKID', 'event_name')},
        ),
    ]
